name: Build APK
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3-setuptools libffi-dev ssl-cert
          pip3 install --user --upgrade buildozer

      - name: Build with Buildozer
        run: |
          # بناء التطبيق مع الموافقة التلقائية على الرخص
          yes | /home/runner/.local/bin/buildozer android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-Android-App
          path: bin/*.apk
          
